# Generated by Django 3.0.4 on 2020-03-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='resolve',
            field=models.BooleanField(default=False),
        ),
    ]
